title: ThruntelliSearch Learning
theme: minima   # or leave blank for default

minima:
  skin: dark

header_pages:
  - index.md          # Home / main page
  - links.md          # If you want "Links" or whatever title it has
  - about.md          # Example extra page